backend:
  # Use netlify identity as backend
  name: "git-gateway"
  branch: "main"
  repo: "https://github.com/AXYS-Creative/portfolio"
media_folder: "src/static/img"
public_folder: "/static/img"
site_url: https://aarongarciacreative1.netlify.app # On admin login page, this adds a 'go back to site' link. Also added in the corner when logged in.
display_url: https://aarongarciacreative1.netlify.app # In admin dashboard, this addes the URL in the corner. Used with 'preview_path' for collection viewing.
logo_url: https://aarongarciacreative1.netlify.app/static/img/admin-logo.svg # On admin login page, this adds a custom logo.

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/posts"
    preview_path: "posts/blog/{{filename}}/"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["Tags", "created", "from", "config.yml"]
      - label: "Cover Image" # Only seems to work with .md collections
        name: "image"
        widget: "image"
        required: false
  - name: "home_page"
    label: "Page - Home"
    description: >
      Edit the site's content here.
    files:
      - name: "marquee"
        label: "Marquee"
        file: "src/_data/marquee.yaml"
        preview_path: "#"
        editor:
          preview: false
        fields:
          - name: "marquee_toggle"
            label: "Marquee Toggle"
            widget: "boolean"
            hint: "Hide or show the marquee."
          - name: "marquee_text"
            label: "Marquee Text"
            widget: "string"
            required: true
          - name: "marquee_text_speech"
            label: "Marquee Text Speech"
            widget: "string"
            hint: "For accessibility, add your message here without any symbols, tokens or classes."
            required: true
      - name: "work_list"
        label: "Work Section"
        file: "src/_data/work_list.yaml"
        preview_path: "#work-list"
        editor:
          preview: false
        fields:
          - name: "work_items"
            label: "Work Items"
            label_singular: "Work Item"
            widget: "list"
            collapsed: false
            fields:
              - {
                  name: "title",
                  label: "Title",
                  widget: "string",
                  required: true,
                }
              - {
                  name: "logo",
                  label: "Business Logo",
                  widget: "image",
                  required: true,
                }
              - {
                  name: "image",
                  label: "Showcase Image",
                  widget: "image",
                  required: true,
                }
              - {
                  name: "background",
                  label: "Background",
                  widget: "select",
                  multiple: false,
                  options: ["dark-bg", "grey-bg", "light-bg", "navy-bg"],
                  default: ["UX Design", "Development"],
                  required: true,
                }
              - {
                  name: "url",
                  label: "Site URL",
                  widget: "string",
                  required: true,
                }
              - {
                  name: "badges",
                  label: "Badges",
                  widget: "select",
                  multiple: true,
                  options:
                    [
                      "UX Design",
                      "Visual Design",
                      "Interaction Design",
                      "Development",
                      "Form Handling",
                      "CMS Setup",
                      "Site Analytics",
                    ],
                  default: ["UX Design", "Development"],
                  required: true,
                }
      - name: "work_gallery"
        label: "Work Gallery"
        file: "src/_data/work_gallery.yaml"
        preview_path: "#work-gallery"
        editor:
          preview: false
        fields:
          - name: "showreel_assets"
            label: "Showreel Assets"
            label_singular: "Showreel Asset"
            widget: "list"
            max: 8
            collapsed: false
            fields:
              - {
                  name: "title",
                  label: "Title",
                  widget: "string",
                  required: true,
                }
              - {
                  name: "media",
                  label: "Media Source",
                  widget: "string",
                  required: true,
                  hint: /static/img/path-to-asset.avif,
                }
              - {
                  name: "class",
                  label: "Custom Class",
                  widget: "string",
                  required: false,
                  hint: Target work item for unique styling,
                }
