backend:
  # Use netlify identity as backend
  name: "git-gateway"
  branch: "main"
  repo: "https://github.com/AXYS-Creative/portfolio"
media_folder: "src/static/img"
public_folder: "/static/img"
site_url: https://aarongarciacreative.com # On admin login page, this adds a 'go back to site' link. Also added in the corner when logged in.
display_url: https://aarongarciacreative.com # In admin dashboard, this addes the URL in the corner. Used with 'preview_path' for collection viewing.
logo_url: https://aarongarciacreative.com/static/img/admin-logo.svg # On admin login page, this adds a custom logo.

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - name: "home_page"
    label: "Page - Home"
    description: >
      Edit the site's content here.
    files:
      - name: "marquee"
        label: "Marquee"
        file: "src/_data/marquee.yaml"
        preview_path: "#"
        editor:
          preview: false
        fields:
          - name: "marquee_toggle"
            label: "Marquee Toggle"
            widget: "boolean"
            hint: "Hide or show the marquee."
          - name: "marquee_text"
            label: "Marquee Text"
            widget: "string"
            required: true
          - name: "marquee_text_speech"
            label: "Marquee Text Speech"
            widget: "string"
            hint: "For accessibility, add your message here without any symbols, tokens or classes."
            required: true
      - name: "work_list"
        label: "Work Section"
        file: "src/_data/work_list.yaml"
        preview_path: "#work-list"
        editor:
          preview: false
        fields:
          - name: "work_items"
            label: "Work Items"
            label_singular: "Work Item"
            widget: "list"
            collapsed: false
            fields:
              - {
                  name: "title",
                  label: "Title",
                  widget: "string",
                  required: true,
                }
              - {
                  name: "logo",
                  label: "Business Logo",
                  widget: "image",
                  required: true,
                }
              - {
                  name: "image",
                  label: "Showcase Image",
                  widget: "image",
                  required: true,
                }
              - {
                  name: "url",
                  label: "Site URL",
                  widget: "string",
                  required: true,
                }
              - {
                  name: "badges",
                  label: "Badges",
                  widget: "select",
                  multiple: true,
                  options:
                    [
                      "UX Design",
                      "Visual Design",
                      "Interaction Design",
                      "Development",
                      "Form Handling",
                      "CMS Setup",
                      "Site Analytics",
                    ],
                  default: ["UX Design", "Development"],
                  required: true,
                }
              - {
                  name: "archive",
                  label: "Archive",
                  widget: "boolean",
                  default: false,
                }
      - name: "work_gallery"
        label: "Work Gallery"
        file: "src/_data/work_gallery.yaml"
        preview_path: "#work-gallery"
        editor:
          preview: false
        fields:
          - name: "axys_clients"
            label: "AXYS Clients"
            label_singular: "AXYS Client"
            widget: "list"
            max: 8
            collapsed: false
            fields:
              - {
                  name: "title",
                  label: "Title",
                  widget: "string",
                  required: true,
                }
              - {
                  name: "media",
                  label: "Media Source",
                  widget: "string",
                  required: true,
                  hint: /static/img/path-to-asset.avif,
                }
              - {
                  name: "poster",
                  label: "Video Poster",
                  widget: "string",
                  required: true,
                  hint: /static/img/path-to-asset.avif,
                }
              - {
                  name: "class",
                  label: "Custom Class",
                  widget: "string",
                  required: false,
                  hint: Target work item for unique styling,
                }
          - name: "rainfocus_clients"
            label: "Rainfocus Clients"
            label_singular: "Rainfocus Client"
            widget: "list"
            max: 8
            collapsed: false
            fields:
              - {
                  name: "title",
                  label: "Title",
                  widget: "string",
                  required: true,
                }
              - {
                  name: "media",
                  label: "Media Source",
                  widget: "string",
                  required: true,
                  hint: /static/img/path-to-asset.avif,
                }
  - name: "partials"
    label: "partials"
    description: >
      Reusable partials to scale your site.
    files:
      - name: "focus_cards"
        label: "Focus Cards"
        file: "src/_data/focus_cards.yaml"
        # preview_path: "#"
        editor:
          preview: false
        fields:
          - name: "section_title"
            label: "Section title"
            widget: "string"
            required: true
          - name: "cards"
            label: "Cards"
            label_singular: "Card"
            widget: "list"
            required: true
            fields:
              - {
                  name: "title",
                  label: "Title",
                  widget: "string",
                  required: true,
                }
              - {
                  name: "title_color",
                  label: "Title Color",
                  widget: "select",
                  multiple: false,
                  options: ["primary", "secondary", "tertiary"],
                  default: "",
                  required: false,
                  hint: "primary = bluey, secondary = bingo, tertiary = pink",
                }
              - {
                  name: "subtitle",
                  label: "Subtitle",
                  widget: "string",
                  required: true,
                }
              - {
                  name: "description",
                  label: "Description",
                  widget: "string",
                  required: true,
                }
  - name: "meta_data"
    label: "Meta Data"
    description: >
      Edit the site's meta data here. Open Graph dimensions: 1200x630. Open graph file name: open-graph.png
    files:
      - name: "meta_data"
        label: "Meta Data"
        file: "src/_data/meta_data.yaml"
        editor:
          preview: false
        fields:
          - name: "site_name"
            label: "Site Name"
            widget: "string"
            required: true
            hint: "Sample Business Co"
          - name: "url"
            label: "URL"
            widget: "string"
            required: true
            hint: "Full URL to your site"
          - name: "author"
            label: "Author"
            widget: "string"
            required: true
            hint: "Person or company name"
          - name: "contact_email"
            label: "Contact Email"
            widget: "string"
            required: true
            hint: "Email address for rich results schema"
          - name: "theme_color"
            label: "Theme Color"
            widget: "color"
            required: true
            hint: "Hex color code for overflow color on some devices"
          - name: "og_title"
            label: "Open Graph Title"
            widget: "string"
            required: true
            hint: "Sample Business | Motto here"
          - name: "og_description"
            label: "Open Graph Description"
            widget: "string"
            required: true
            hint: "Keep at least 100 characters"
          - name: "og_img"
            label: "Open Graph Image"
            widget: "image"
            default: "https://aarongarciacreative.com/static/img/open-graph.png"
            required: true
            hint: "Recommended formats: PNG or JPG. Recommended image dimensions: 1200 x 630 pixels. File size should be under 8 MB."
